### ISSUE TITLE
Insert a new braile symbol 

### ISSUE THREAD

**Issue by Joycitta** [mateuswetah/BrailleEcran#1]
dot - 3

Check if the dot has another value.

**Comment by mateuswetah** [comment]
No it doesn't. Which symbol would be?

**Comment by Joycitta** [comment]
"Dot" symbol. 

In Braille, the "full stop" is number 3.

**Comment by mateuswetah** [comment]
Oh ok, you mean the the "period" mark. 
That is already available, but I don't know why i was using the wrong combination (2-5-6).

Going to fix it to v1.0.2
