### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by Joycitta** [mateuswetah/BrailleEcran#3]
Replace -- by ;

Instanciado este arquivo de Log -- domingo abril 9; 11:10:45; 2017
Instanciado este arquivo de Log ; domingo abril 9; 11:10:45; 2017

**Comment by mateuswetah** [comment]
Maybe a figure like "123 (with the squared button) + 5 for help".
We could put it above the dot buttons.

**Comment by mateuswetah** [comment]
Will be out in v1.0.2
