### ISSUE TITLE
Refresh layout

### ISSUE THREAD

**Issue by Joycitta** [mateuswetah/BrailleEcran#5]
Insert "Help Center" and "Settings Panel" icons. 
![screen](https://cloud.githubusercontent.com/assets/27175429/25683983/1ee51d68-3035-11e7-8935-7fb11867ac99.png)

**Comment by mateuswetah** [comment]
Done. Although I'm almost certain this alignment won't be perfect in every device...
Coming out next version.
![photo_2017-05-03_21-15-00](https://cloud.githubusercontent.com/assets/1184874/25686545/9b2b4522-3045-11e7-8b85-e78cc21f9e48.jpg)
