### ISSUE TITLE
The application closes

### ISSUE THREAD

**Issue by Joycitta** [mateuswetah/BrailleEcran#6]
The application closes when you send a blank message.

**Comment by mateuswetah** [comment]
Weird... I can't emulate that. Technicaly, if you attempt to send an empty message, it should speak "Empty message." before even trying to send the sms. I also tested with just white spaced message and it worked.

**Comment by Joycitta** [comment]
Try send the message with braille dots selected.

**Comment by mateuswetah** [comment]
Ok, got it. Solved for next version.
